apiVersion: v1
kind: ConfigMap
data:
  mosquitto.conf: |-
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout

    listener 8883
    protocol mqtt
    allow_anonymous false
    cafile /mosquitto/certs/ca.crt
    keyfile /mosquitto/certs/server.key
    certfile /mosquitto/certs/server.crt
    require_certificate true
    use_identity_as_username true

    listener 9090
    protocol websockets
    allow_anonymous false
metadata:
  name: mosquitto-config
  namespace: offgrid
