apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  name: mosquitto
  namespace: offgrid
spec:
  ports:
  - name: mqtt
    nodePort: 31883
    port: 8883
    protocol: TCP
    targetPort: mqtt
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  type: NodePort
