apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: offgrid
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: '1Gi'
  storageClassName: ceph-rbd
