[package]
name = "offgrid"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
linkme = "0.3.27"
log = "0.4.22"
log4rs = "1.3.0"
morse = {path = "../morse"}
serde = "1.0.204"
tokio = {version = "1.38.0", features = ["full"]}
tokio-modbus = "0.14.0"
tokio-serial = "5.4.4"
