connect:
      gtkterm -p /dev/ttyUSB0 -s 9600

      #  -p, --port <device>
      #         Serial port device (default /dev/ttyS0).

      #  -s, --speed <speed>
      #         Serial port speed (default 115200).

      #  -b, --bits <bits>
      #         Number of bits (default 8).

      #  -t, --stopbits <stopbits>
      #         Number of stopbits (default 1).

      #  -a, --parity <odd | even>
      #         Partity (default none).

      #  -w, --flow <Xon | CTS>
      #         Flow control (default none).

      #  -d, --delay <ms>
      #         End of line delay in ms (default none).

      #  -r, --char <char>
      #         Wait for a special char at end of line (default none).

      #  -f, --file <filename>
      #         Default file to send (default none).

      #  -e, --echo
      #         Set local echo.

      #  -x, --rts_time_before <ms>
      #         For rs485, time in ms before transmit with rts on

      #  -y, --rts_time_after <ms>
      #         For rs485, time in ms after transmit with rts on

      #  -e, --echo
      #         Switch on local echo

      #  -L, --disable-port-lock
      #         Do not lock serial port. Allows to send to serial port from different terminals.
