appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {M}:{L} — {m}{n}"
  log_file:
    kind: file
    path: "log/morse_pff.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {M}:{L} — {m}{n}"

root:
  level: info
  appenders:
    - stdout
    - log_file